# -*- coding: utf-8 -*-
"""CAPSTONE PROJECT 1A

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wA-nEAFY2lj4FRW63BkcHqK60flgKGoX

Topic: Spam Email Classifiers

**# 1. Import Necessary Libraries**
"""

import numpy as np
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
import seaborn as sns
import matplotlib.pyplot as plt

import nltk

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

"""## 1.1. Import Dataset from Kaggle"""

df = pd.read_csv('/content/sms_spam.csv')

"""# 2. Viewing Properties of Dataset

2.1 Vieing Shape of Dataframe
This shows that they are 2 columns and 5,559 rows in the data set.
"""

df.shape

"""2.2. Dataset information;
This gives a summary of the information contained in the dataset as it concerns the number of entries, rows/columns, datatype, missing values etc
"""

df.info()

"""2.3 ;Dataset Preview - from head or tail:
This displays a range of the set, either from the top or bottome entries.
"""

df.head(20)

df.tail()

"""## 2.4 Describing the dataframe:
This gives the statistical analysis of the dataset where necessary.
"""

df.describe()

df.describe().T

import pandas as pd
import numpy as np
import re
import string
import matplotlib.pyplot as plt

# Count Spam and Ham messages
class_counts = df['type'].value_counts()

# If labels were converted to numbers
class_counts.index = ['Ham', 'Spam']

# Create bar chart
plt.figure(figsize=(6,4))
plt.bar(class_counts.index, class_counts.values)

plt.title('Distribution of SMS Messages')
plt.xlabel('Message Type')
plt.ylabel('Count')

for i, v in enumerate(class_counts.values):
    plt.text(i, v + 20, str(v), ha='center')

plt.show()

"""# 3. Cleaning Dataset

## 3.1. Checking for Missing Values.
This show if there are missing enteries and the data type, whether it is a string, int, bollian or float.

##
"""

df.isnull().sum()

"""## 3.2. Checking for Duplicate:
This checks if they are duplicate entries in the dataframe.
The output below shows that they are 403 uplicates in the entry and all are of the INT data type.
"""

df.duplicated().sum()

"""## 3.2.1. After Dropping Duplicate.
On dropping 403 duplicated entries from the 5,559 entries, it remaining 5,156 rows arranged in 2 columns.
"""

df = df.drop_duplicates()
df.shape # Display new shape

"""# 4. Trainig the Dataset
This generates a Random Forec classifier, using the training data into X train (Training_input_data) and y train (Training_output_data), which will them make prediction on the data.
"""

vectorizer = TfidfVectorizer(stop_words='english', lowercase=True,
    max_features=3000,  # Limit features
    ngram_range=(1, 2),  # Include bigrams
    min_df=2,            # Remove rare words
    max_df=0.9           # Remove very common words
)

import string

def preprocess_text(text):
    """Comprehensive text preprocessing"""
    # Convert to lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Remove numbers
    text = re.sub(r'\d+', '', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# Apply preprocessing
df['text'] = df['text'].apply(preprocess_text)

df = df.copy() # Create a defensive copy to avoid SettingWithCopyWarning

# Replace 'ham' with 0 and 'spam' with 1.
# This operation will only affect values that are 'ham' or 'spam'.
# If the column already contains 0/1 integers, it will not change them.
df['type'] = df['type'].replace({'ham': 0, 'spam': 1})

# Ensure the column is of integer type. Any non-convertible values will raise an error here.
df['type'] = df['type'].astype(int)

df.head() # Display head to confirm conversion

X = vectorizer.fit_transform(df['text'])
y = df['type']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = RandomForestClassifier(n_jobs=-1)
clf.fit(X_train, y_train)

"""## 4.1. Testing and Predicting Dataset

The output is classified into Ham (likely non-Spam messages in a string datatype


"""

y_pred = clf.predict(X_test)
y_pred

# 5. Evaluating the Performnce and visuslization

"""## 5. Performance Classification, Prediction and Visualization

This evaluates:
1. The accuracy score (y_test, y_pred), calculating the correct prediction, where output is 0.9712 or 97.12%

2. The confusion matrix (y_test, y_pred), which creates a table showing the true against the predicted labels i.e the counts of correct against the incorrect classifications).
3. sns.headmap which visualizes the confusion matrix with annotated counts as true

4. plt.show(), which displays the heatmap plot

"""

score = accuracy_score(y_test, y_pred)
print("Score: ", score)
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d")
plt.show()

"""## TRIANING THE MACHINE LEARNING MODEL

"""

### **4. Handle Class Imbalance**
from sklearn.utils.class_weight import compute_class_weight

# Check class distribution
print(df['type'].value_counts())

# Use class weights for imbalanced data
class_weights = compute_class_weight('balanced', classes=np.unique(y), y=y)
class_weight_dict = dict(enumerate(class_weights))

# Pass to classifier
clf = RandomForestClassifier(
    n_estimators=200,
    class_weight=class_weight_dict,
    random_state=42,
    n_jobs=-1
)

"""###Neural Network"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# from sklearn.neural_network import MLPClassifier
# 
# mlp_classifier_model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000)
# mlp_classifier_model.fit(X_train, y_train)
# 
# prediction = mlp_classifier_model.predict(X_test)
# 
# # Calculate and print classification metrics
# print("MLP Classifier")
# print("Accuracy score: {:.2f}".format(accuracy_score(y_test, prediction)))
# print("Precision score: {:.2f}".format(precision_score(y_test, prediction, pos_label=1)))
# print("Recall score: {:.2f}".format(recall_score(y_test, prediction, pos_label=1)))
# print("F1 score: {:.2f}".format(f1_score(y_test, prediction, pos_label=1)))

"""###Multinomial Naive Bayes"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Multinomial Naive Bayes model
# from sklearn.naive_bayes import MultinomialNB
# 
# multinomial_nb_model = MultinomialNB()
# multinomial_nb_model.fit(X_train, y_train)  # Train the model
# 
# prediction = multinomial_nb_model.predict(X_test)
# 
# print("Multinomial NB")
# print("Accuracy score: {}".format(accuracy_score(y_test, prediction)))
# print("Precision score: {}".format(precision_score(y_test, prediction, pos_label=1)))
# print("Recall score: {}".format(recall_score(y_test, prediction, pos_label=1)))
# print("F1 score: {}".format(f1_score(y_test, prediction, pos_label=1)))

"""###Bernoulli Naive Bayes"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Bernoulli Naive Bayes model
# from sklearn.naive_bayes import BernoulliNB
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# 
# bernoulli_nb_model = BernoulliNB()
# bernoulli_nb_model.fit(X_train, y_train)
# 
# prediction = bernoulli_nb_model.predict(X_test)
# 
# #Evaluation
# print("Bernoulli NB")
# print("Accuracy score: {}".format(accuracy_score(y_test, prediction)) )
# print("Precision score: {}".format(precision_score(y_test, prediction, pos_label=1)) )
# print("Recall score: {}".format(recall_score(y_test, prediction, pos_label=1)))
# print("F1 score: {}".format(f1_score(y_test, prediction, pos_label=1)))

"""### EVALUATION METRICS"""

### **5. Enhanced Evaluation Metrics**
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report, roc_auc_score, roc_curve

# Ensure the classifier is fitted before use
# This addresses the NotFittedError if clf was re-initialized without fitting
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
y_pred_proba = clf.predict_proba(X_test)[:, 1]

print("=" * 50)
print("DETAILED CLASSIFICATION REPORT")
print("=" * 50)
print(classification_report(y_test, y_pred, target_names=['Ham', 'Spam']))

print(f"\nROC AUC Score: {roc_auc_score(y_test, y_pred_proba):.4f}")

# Visualize ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_pred_proba)
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label='ROC Curve')
plt.plot([0, 1], [0, 1], 'k--', label='Random')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend()
plt.show()

"""###CONFUSION METRICS"""

from sklearn.metrics import confusion_matrix
models = [("Multinomial NB", multinomial_nb_model), ("Bernoulli NB", bernoulli_nb_model),("MLP Classifier", mlp_classifier_model) ]

fig, axes = plt.subplots(1, 3, figsize=(10, 3))
for i, (model_name, model) in enumerate(models):
    prediction = model.predict(X_test)
    cm = confusion_matrix(y_test, prediction)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False, ax=axes[i])
    axes[i].set_title(f"{model_name} - Confusion Matrix")
    axes[i].set_xlabel("Predicted")
    axes[i].set_ylabel("Actual")
plt.tight_layout()
plt.show()

"""###Metric Comparison Heatmap"""

metric_data = []
for model_name, model in models:
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    precision = precision_score(y_test, prediction, pos_label=1)
    recall = recall_score(y_test, prediction, pos_label=1)
    f1 = f1_score(y_test, prediction, pos_label=1)
    metric_data.append([accuracy, precision, recall, f1])
metric_labels = ["Accuracy", "Precision", "Recall", "F1 Score"]
#heatmap for metric comparison
plt.figure(figsize=(6, 3))
sns.heatmap(metric_data, annot=True, fmt=".2f", cbar=False, cmap="summer_r", xticklabels=metric_labels, yticklabels=[model_name for model_name, _ in models])
plt.title("Metric Comparison")
plt.yticks(rotation=0)
plt.xlabel("Metrics")
plt.ylabel("Models")
plt.tight_layout()
plt.show()

import joblib

# Save the trained model and vectorizer
joblib.dump(clf, 'spam_email_classifier_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')
print("Model and vectorizer saved successfully.")

!pip install streamlit
import streamlit as st
import joblib
import numpy as np

model = joblib.load("spam_email_classifier_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

st.title("🔒 Spam Email Classifier")

email_text = st.text_area("Enter Email Text", placeholder="Paste your email here...")

if st.button("Classify Email"):
    if email_text.strip() == "":
        st.warning("⚠️ Please enter email text to classify.")
    else:
        transformed = vectorizer.transform([email_text])
        prediction = model.predict(transformed)
        confidence = model.predict_proba(transformed).max()

        if prediction[0] == 1:
            st.error(f"🚨 **Spam Detected** (Confidence: {confidence:.2%})")
        else:
            st.success(f"✅ **Legitimate Email** (Confidence: {confidence:.2%})")

        # Show top spam indicators
        st.markdown("---")
        st.info(f"Classification Confidence: {confidence:.2%}")

!pip freeze > requirements.text